
@baseurl=http://localhost:8081/api
@test200_MacID=52-3C-42-D4-A9-F4
@test404_MacID=26-97-ED-E5-FB-ED
### Negative test to add device with invalid configuration

POST {{baseurl}}/devices
Content-Type: application/json

{
    "name": "Aquaponics pump control-I@Saidham",
    "make" :"Raspberry Pi 0w 512M 16G",
    "mac": "52-3C-42-D4-A9-F0",
    "location": "18.41827883006836, 73.76921566514285",
    "users": [
        "kneerunjun@gmail.com",
        "awatiniranjan@gmail.com"
    ],
    "cfg": {
        "tickat": "",
        "config": 1,
        "interval": 100,
        "pulsegap": 80
    }
}

### Negative test to add device with invalid mac 
POST {{baseurl}}/devices
Content-Type: application/json

{
    "name": "Aquaponics pump control-I@Saidham",
    "make" :"Raspberry Pi 0w 512M 16G",
    "mac": "",
    "location": "18.41827883006836, 73.76921566514285",
    "users": [
        "kneerunjun@gmail.com",
        "awatiniranjan@gmail.com"
    ],
    "cfg": {
        "tickat": "12:00",
        "config": 0,
        "interval": 100,
        "pulsegap": 80
    }
}

### Negative test to add device with no users
POST {{baseurl}}/devices
Content-Type: application/json

{
    "name": "Aquaponics pump control-I@Saidham",
    "make" :"Raspberry Pi 0w 512M 16G",
    "mac": "52-3C-42-D4-A9-F0",
    "location": "18.41827883006836, 73.76921566514285",
    "users": [],
    "cfg": {
        "tickat": "12:00",
        "config": 0,
        "interval": 100,
        "pulsegap": 80
    }
}


### trying to get a device whos mac id isnt registered

GET {{baseurl}}/devices/{{test404_MacID}}

### deleting a device registration that does not exists 

DELETE  {{baseurl}}/devices/{{test404_MacID}}