apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-appdata
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/eensyaquap/mongo"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-appdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi